---
title: "Documents of Application"
author:
  firstname: Oliver
  lastname: Rehren
  contact:
    - icon: fa address-card
      text: "Bernsdorfer Str. 19, 09126 Chemnitz, Germany"
    - icon: fa mobile-screen
      text: "+49 163 69 69 603"
    - icon: fa envelope
      text: o.rehren@gmail.com
      url: "mailto:o.rehren@gmail.com"
  socialmedia: 
    - icon: fa house 
      text: example.com
      url: https://example.com
    - icon: fa orcid
      text: 0000-0001-7602-8219
      url: https://orcid.org/0000-0001-7602-8219
    - icon: fa github
      text: GitHub
      url: https://github.com/orehren
    - icon: fa linkedin
      text: LinkedIn
      url: https://de.linkedin.com/in/oliver-rehren-097854248
position: Psychologist and Data Scientist
style:
  color-accent: "5e81ac" # Ein Blauton
  font-header: "Lato"
  font-text: "Roboto"
profile-photo: "../../../_src/me.jpg" # Optional
aboutme: |
    Passionated and curious research scientist with extensive knowledge of core 
    concepts of (media) psychology, especially on the intersection between 
    empathy and anthropomorphism in the human robotic interaction, as well as 
    computational frameworks, dataset design and advanced statistical methods. 
    Capable of using research skills to understand experimental databases and 
    prepare results for the public communication in the scientific community and 
    beyond. Convinced of the interdisciplinary research approach and collaborating 
    with team members and other researchers to enhance people’s lives.
famous-quote: # Optional
  text: "Nothing is as practical as a good theory."
  attribution: "Kurt Lewin"
format: academiccvtoolstemplate-typst
---

```{r}
#| label: lst-setup
#| include: false

library(tidyverse)
library(googledrive)
library(googlesheets4)
library(academicCVtools)

# Authentifizierung
drive_auth()
gs4_auth(token = drive_token())

# Sheet List
cv_sheets_list <- list(
  "Working Experiences",
  "Education",
  "IT Skills", 
  "Language Skills",
  # "Raised Fundings" = "funds",
  "Reviewer",
  "Institutional Services",
  "Research Interests",
  "Additional Academic Activity",
  "Teaching Experiences",
  "Training and Professional Development",
  "Other Employments",
  "Social Engagement",
  "Internships"
)

cv_sheets <- load_cv_sheets(
  doc_identifier = "Application_CV_Data",
  #sheets_to_load = "*"
  sheets_to_load = cv_sheets_list
)

```

## Research Interests

```{r}
#| output: asis
#| label: lst-research_interests

cv_sheets$research_interests |> format_typst_section(typst_func = "#research-interests") |> cat()

```

## Working Experiences

```{r}
#| output: asis
#| label: lst-work

cv_sheets$working_experiences |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Education

```{r}
#| output: asis
#| label: lst-education

cv_sheets$education |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start",
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry", 
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Raised Fundings

```r
#| output: asis
#| label: lst-funds

cv_sheets$raised_fundings |>
format_typst_section(
                       typst_func = "#resume-entry", 
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Publications List

```{r}
#| output: asis

create_publication_list(bib_file = "_src/bibliography.bib", 
                        author_name = "Rehren, O.", 
                        csl_file = "_src/apa.csl",
                        group_labels = c(
                          article = "Journal Articles",
                          inproceedings = "Conference Papers",
                          incollection = "Book Chapters",
                          misc = "In Preparation"
                          ), 
                        default_label = "Other",
                        group_order = c("Journal Article", "Book Chapter", "Conference Paper", "Miscellaneous"),
                        pandoc_path = NULL,
                        #author_highlight_markup = "#strong[%s]"
                        author_highlight_markup = '#text(fill: rgb("516db0"), weight: "bold")[%s]'
                        #author_highlight_markup = "#strong[#text(color-accent)[%s]]"
                        ) |> cat()
```

## Institutional Services

```{r}
#| output: asis
#| label: lst-institute

cv_sheets$institutional_services |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start",
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry", 
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Additional Academic Activity

```{r}
#| output: asis
#| label: lst-activity

cv_sheets$additional_academic_activity |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()
```

## Teaching Experiences

```{r}
#| output: asis
#| label: lst-teaching

cv_sheets$teaching_experiences |>
  # arrange(
  #         desc(end),
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start",
  #                   end_col = "end",
  #                   output_col = "date",
  #                   output_format = "%m/%Y",
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry", 
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Training and Professional Development

```{r}
#| output: asis
#| label: lst-training

cv_sheets$training_and_professional_development |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Internships

```{r}
#| output: asis
#| label: lst-internships

cv_sheets$internships |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()

```

## Reviewer

```{r}
#| output: asis
#| label: lst-reviewer

cv_sheets$reviewer |>
  format_typst_section(
    typst_func = "#resume-entry",
    combine_cols = c(starts_with("detail")), #_2:detail_7), 
    combine_as = "details", 
    combine_prefix = "· "
  ) |> cat()
```

## Social Engagement

```{r}
#| output: asis
#| label: lst-social

cv_sheets$social_engagement |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()

```


## Language Skills

```{r}
#| output: asis
#| label: lst-language

cv_sheets$language_skills |>
 format_typst_section(
   typst_func = "#visualize-skills-list",
   output_mode = "array"
 ) |> cat()
  
```

## Tech Stack

```{r}
#| output: asis
#| label: lst-tech

cv_sheets$it_skills |>
 format_typst_section(
   typst_func = "#visualize-skills-list",
   output_mode = "array"
 ) |> cat()
  
```

## Employments

```{r}
#| output: asis
#| label: lst-other

cv_sheets$other_employments |>
  # arrange(
  #         desc(end), 
  #         desc(start)
  #         ) |>
  # format_date_range(
  #                   start_col = "start", 
  #                   end_col = "end", 
  #                   output_col = "date", 
  #                   output_format = "%m/%Y", 
  #                   sep = " - "
  #                   ) |>
  format_typst_section(
                       typst_func = "#resume-entry",
                       combine_cols = c(dplyr::starts_with("detail")),
                       combine_as = "details",
                       combine_sep = "\\ \\ ",
                       combine_prefix = "· ",
                       exclude_cols = c(start, end)
                       ) |> cat()

```


