#' Load Multiple Sheets from a Google Sheet
#'
#' Reads data from multiple sheets of a Google Sheet document and returns them
#' as tibbles in a named list.
#'
#' @details This function serves as a high-level wrapper around `read_cv_sheet`.
#'   It validates its arguments and then prepares a loading configuration based
#'   on the `sheets_to_load` parameter. It iteratively calls `read_cv_sheet` for
#'   each specified sheet and assigns the resulting tibble to the correct name
#'   in the output list.
#'
#' @param doc_identifier A character string representing the ID, URL, or a unique
#'   name of the target Google Sheets document.
#' @param sheets_to_load A list or character vector specifying which sheets to
#'   load.
#'   \itemize{
#'     \item **Named List/Vector**: The names of the list should be the exact
#'       sheet names (tabs) to read (e.g., `"Working Experiences"`), and the
#'       values should be the desired names for the list elements in the output
#'       (e.g., `"work_exp"`).
#'     \item **Unnamed Character Vector**: A vector of the exact sheet names to
#'       read. The output list names will be automatically generated by cleaning
#'       the sheet names.
#'   }
#' @param ... Additional arguments passed down to `read_cv_sheet` for every
#'   sheet being loaded (e.g., `na_strings`, `col_types`).
#'
#' @return A named list where each element is a `tibble` of data from a sheet.
#'
#' @export
load_cv_sheets <- function(doc_identifier,
                           sheets_to_load,
                           ...) {

  .validate_load_cv_sheets_args(doc_identifier, sheets_to_load, ...)

  ss_input <- .resolve_doc_identifier(doc_identifier)

  load_config <- .prepare_sheet_load_config(sheets_to_load, ss_input = ss_input)

  if (length(load_config$sheet_names_to_read) == 0) {
    cli::cli_inform("No sheets specified or found to load. Returning an empty list.")
    return(list())
  }

  loaded_data_list_unnamed <- .load_sheets_data(
    sheet_names_to_read = load_config$sheet_names_to_read,
    doc_identifier,
    !!!rlang::list2(...)
  )

  loaded_data_list_named <- purrr::set_names(
    loaded_data_list_unnamed,
    load_config$target_list_names
  )

  return(loaded_data_list_named)
}
