#' Load Multiple Sheets from a Google Sheet
#'
#' Reads data from multiple sheets of a Google Sheet document and returns them
#' as tibbles in a named list.
#'
#' @details This function serves as a high-level wrapper around `read_cv_sheet`.
#'   It validates its arguments and then prepares a loading configuration based
#'   on the `sheets_to_load` parameter. It iteratively calls `read_cv_sheet` for
#'   each specified sheet and assigns the resulting tibble to the correct name
#'   in the output list.
#'
#' @param doc_identifier A character string representing the ID, URL, or a unique
#'   name of the target Google Sheets document.
#' @param sheets_to_load A list or character vector specifying which sheets to
#'   load.
#'   \itemize{
#'     \item **Named List/Vector**: The names of the list should be the exact
#'       sheet names (tabs) to read (e.g., `"Working Experiences"`), and the
#'       values should be the desired names for the list elements in the output
#'       (e.g., `"work_exp"`).
#'     \item **Unnamed Character Vector**: A vector of the exact sheet names to
#'       read. The output list names will be automatically generated by cleaning
#'       the sheet names.
#'   }
#' @param ... Additional arguments passed down to `read_cv_sheet` for every
#'   sheet being loaded (e.g., `na_strings`, `col_types`).
#'
#' @return A named list where each element is a `tibble` of data from a sheet.
#'
#' @export
load_cv_sheets <- function(doc_identifier,
                           sheets_to_load,
                           ...) {

  .validate_load_cv_sheets_args(doc_identifier, sheets_to_load, ...)

  ss_input <- .resolve_doc_identifier(doc_identifier)

  load_config <- .prepare_sheet_load_config(sheets_to_load, ss_input = ss_input)

  if (length(load_config$sheet_names_to_read) == 0) {
    return(list())
  }

  # We query the API for available sheets to filter the request list.
  # This is necessary for polyglot pipelines where the config might contain
  # sheets that exist in local files but not in this specific Google Doc.
  available_sheets <- tryCatch(
    googlesheets4::sheet_names(ss_input),
    error = function(e) {
      cli::cli_warn("Could not retrieve sheet names. Proceeding without validation.")
      return(NULL)
    }
  )

  if (!is.null(available_sheets)) {
    valid_indices <- which(load_config$sheet_names_to_read %in% available_sheets)

    # We must filter both vectors synchronously to maintain the mapping
    # between the source sheet name and the target list key.
    if (length(valid_indices) < length(load_config$sheet_names_to_read)) {
      load_config$sheet_names_to_read <- load_config$sheet_names_to_read[valid_indices]
      load_config$target_list_names   <- load_config$target_list_names[valid_indices]
    }
  }

  if (length(load_config$sheet_names_to_read) == 0) {
    return(list())
  }

  loaded_data_list_unnamed <- .load_sheets_data(
    sheet_names_to_read = load_config$sheet_names_to_read,
    doc_identifier,
    !!!rlang::list2(...)
  )

  loaded_data_list_named <- purrr::set_names(
    loaded_data_list_unnamed,
    load_config$target_list_names
  )

  return(loaded_data_list_named)
}



#' Prepare Sheet Loading Configuration
#'
#' Internal helper to determine the exact sheet names to read and the desired
#' names for the output list elements based on the `sheets_to_load` argument.
#'
#' @param sheets_to_load A named list/vector, an unnamed character vector, or the
#'   string `"*"`.
#' @param ss_input The resolved Google Sheet identifier (ID string, URL string,
#'   or dribble), required if `sheets_to_load` is `"*"`.
#'
#' @return A list with two elements: `sheet_names_to_read` (character vector)
#'   and `target_list_names` (character vector).
#'
#' @noRd
.prepare_sheet_load_config <- function(sheets_to_load, ss_input = NULL) {

  sheet_names_to_read <- NULL
  target_list_names <- NULL

  is_special_wildcard <- is.character(sheets_to_load) && length(sheets_to_load) == 1 && sheets_to_load == "*"

  if (is_special_wildcard) {
    if (is.null(ss_input)) {
      cli::cli_abort("Internal error: {.arg ss_input} must be provided when {.arg sheets_to_load} is \"*\".", call. = FALSE)
    }
    cli::cli_inform("Fetching all sheet names from the document...")
    sheet_names_to_read <- tryCatch({
      googlesheets4::sheet_names(ss_input)
    }, error = function(e) {
      cli::cli_abort("Failed to retrieve sheet names from the document when 'sheets_to_load = \"*\"'.", parent = e, call. = FALSE)
    })

    if (length(sheet_names_to_read) == 0) {
      cli::cli_warn("No sheets found in the document or failed to retrieve names.")
      return(list(sheet_names_to_read = character(0), target_list_names = character(0)))
    }

    target_list_names <- gsub("[^[:alnum:]_]+", "_", tolower(sheet_names_to_read))
    cli::cli_inform("Using all {length(sheet_names_to_read)} sheets found: {paste(shQuote(sheet_names_to_read), collapse = ', ')}. Target list names: {.val {target_list_names}}")

  } else {
    if (rlang::is_named(sheets_to_load)) {
      sheet_names_to_read <- names(sheets_to_load)
      target_list_names <- as.character(unlist(sheets_to_load))
    } else {
      sheet_names_to_read <- sheets_to_load
      target_list_names <- gsub("[^[:alnum:]_]+", "_", tolower(sheet_names_to_read))
      cli::cli_inform(
        "Using cleaned sheet names as names for the returned list: {.val {target_list_names}}"
      )
    }
  }

  return(list(
    sheet_names_to_read = sheet_names_to_read,
    target_list_names = target_list_names
  ))
}

#' Load Data for Multiple Sheets
#'
#' Internal helper that iteratively calls `read_cv_sheet` for a list of sheet
#' names.
#'
#' @param sheet_names_to_read A character vector of sheet names to read.
#' @param doc_identifier The resolved document identifier (ID, URL, or dribble).
#' @param ... Additional arguments to pass down to `read_cv_sheet`.
#'
#' @return A list of tibbles, one for each sheet.
#'
#' @noRd
.load_sheets_data <- function(sheet_names_to_read, doc_identifier, ...) {
  cli::cli_inform("Starting data loading for {length(sheet_names_to_read)} sheet(s)...")

  read_from_specific_doc <- purrr::partial(
    read_cv_sheet,
    doc_identifier = doc_identifier,
    ...
  )

  loaded_data_list <- purrr::map(
    sheet_names_to_read,
    ~ {
      cli::cli_inform("--> Loading sheet {.val {.x}}...")
      read_from_specific_doc(sheet_name = .x)
    }
  )

  cli::cli_inform("...Data loading finished.")
  return(loaded_data_list)
}


#' Validate Arguments for `load_cv_sheets`
#'
#' An internal helper function that uses `checkmate` assertions to validate all
#' arguments passed to the `load_cv_sheets` function.
#'
#' @param doc_identifier The Google Sheet identifier.
#' @param sheets_to_load The specification of sheets to load.
#' @param ... Additional arguments (currently unused, for extensibility).
#'
#' @return `TRUE` (invisibly) if all checks pass, otherwise aborts with an error.
#' @noRd
.validate_load_cv_sheets_args <- function(doc_identifier, sheets_to_load, ...) {
  checkmate::assert_string(doc_identifier, min.chars = 1)
  if (is.character(sheets_to_load)) {
    checkmate::assert_character(sheets_to_load, min.chars = 1, min.len = 1)
  } else if (rlang::is_named(sheets_to_load)) {
    checkmate::assert_list(sheets_to_load, types = "character", names = "unique")
  } else {
    checkmate::assert_list(sheets_to_load, types = "character")
  }
}
