# R/load_cv_sheets.R

#' Load multiple sheets from a Google Sheet into a named list
#'
#' This function reads data from multiple specified sheets of a single Google
#' Sheet document and returns them as tibbles within a named list. It validates
#' arguments before proceeding using assertions from the `checkmate` package via
#' an internal helper function.
#'
#' @param doc_identifier The ID, URL, or name of the Google Sheets document.
#'        Must be a single, non-empty string. Passed to `read_cv_sheet`.
#' @param sheets_to_load A named list or character vector defining which sheets
#'        to load and how to name the results in the output list.
#'        - If **named list/vector**: Names must be the sheet names (tabs) to read
#'          (e.g., `"Working Experiences"`), and values must be the desired
#'          character names for the corresponding list elements in the output
#'          (e.g., `"work_exp"`). Example: `list("Working Experiences" = "work_exp")`.
#'          Names and values must be non-empty strings.
#'        - If **unnamed character vector**: A vector of sheet names (tabs) to read
#'          (e.g., `c("Working Experiences", "Education")`). The names of the
#'          returned list elements will be automatically generated by cleaning
#'          the sheet names (using `janitor::make_clean_names`). Sheet names
#'          must be non-empty strings.
#' @param ... Additional arguments to be passed down to `read_cv_sheet` for
#'        every sheet being read (e.g., `na_strings`, `col_types`).
#'
#' @return A named list where each element is a `tibble` containing the data
#'         from a requested sheet. The names of the list elements are determined
#'         as described for `sheets_to_load`.
#'
#' @importFrom purrr map set_names map_chr
#' @importFrom rlang list2
#'
#' @export
#'
#' @examples
#' \dontrun{
#' # Requires authentication beforehand, e.g., via gs4_auth() / drive_auth()
#' # doc_id <- "YOUR_SHEET_ID_OR_URL_OR_NAME" # Replace with your identifier
#'
#' # --- Example 1: Using a named list for sheets_to_load ---
#' my_cv_sheets_named <- list(
#'   "Working Experiences" = "work_experience", # Sheet name -> desired list name
#'   "Education" = "education_history",
#'   "Skills" = "skills_data" # Assuming these sheets exist
#' )
#' try(
#'   {
#'     cv_data_named <- load_cv_sheets(
#'       doc_identifier = doc_id,
#'       sheets_to_load = my_cv_sheets_named
#'     )
#'     # Access data via assigned names:
#'     print(names(cv_data_named))
#'     # print(head(cv_data_named$work_experience))
#'     # print(head(cv_data_named$education_history))
#'   },
#'   silent = TRUE
#' )
#'
#' # --- Example 2: Using an unnamed vector for sheets_to_load ---
#' # Assumes janitor package is installed
#' my_cv_sheets_unnamed <- c("Working Experiences", "Education", "Skills & Awards")
#' # Note: "Skills & Awards" will become "skills_awards"
#' try(
#'   {
#'     cv_data_unnamed <- load_cv_sheets(
#'       doc_identifier = doc_id,
#'       sheets_to_load = my_cv_sheets_unnamed
#'     )
#'     # Access data via cleaned names:
#'     print(names(cv_data_unnamed))
#'     # print(head(cv_data_unnamed$working_experiences))
#'     # print(head(cv_data_unnamed$education))
#'     # print(head(cv_data_unnamed$skills_awards))
#'   },
#'   silent = TRUE
#' )
#'
#' # --- Example 3: Passing extra arguments to read_cv_sheet ---
#' try(
#'   {
#'     cv_data_char <- load_cv_sheets(
#'       doc_identifier = doc_id,
#'       sheets_to_load = my_cv_sheets_unnamed, # Use unnamed list from above
#'       col_types = "c" # Read all as character for all sheets loaded
#'     )
#'     # Verify column types in one of the tibbles
#'     # print(lapply(cv_data_char$working_experiences, class))
#'   },
#'   silent = TRUE
#' )
#'
#' # --- Example 4: Invalid sheets_to_load (should error via checkmate) ---
#' invalid_sheets_config <- list(
#'   "Work" = "work_df",
#'   Experience = 123 # Invalid type
#' )
#' try(
#'   {
#'     load_cv_sheets(doc_identifier = doc_id, sheets_to_load = invalid_sheets_config)
#'   },
#'   error = function(e) {
#'     print(paste("Successfully caught expected error:", e$message))
#'   }
#' )
#' }
load_cv_sheets <- function(doc_identifier,
                           sheets_to_load,
                           ...) {

  # ============================================================================
  # Phase 0: Validate Arguments
  # ============================================================================
  # Call the dedicated validation function (defined in validation_helpers.R)
  # Aborts on failure.
  .validate_load_cv_sheets_args(doc_identifier, sheets_to_load, ...)

  ss_input <- .resolve_doc_identifier(doc_identifier)
  # ============================================================================
  # Phase 1: Prepare Loading Configuration
  # ============================================================================
  # Call helper to get sheet names and target names
  # (Defined in load_cv_sheets_helpers.R)
  load_config <- .prepare_sheet_load_config(sheets_to_load, ss_input = ss_input)

  # Guard Clause: If no sheets to read (e.g., "*" on empty doc, or empty list)
  if (length(load_config$sheet_names_to_read) == 0) {
    cli::cli_inform("No sheets specified or found to load. Returning an empty list.")
    return(list())
  }

  # ============================================================================
  # Phase 2: Load Data Iteratively
  # ============================================================================
  # Call helper to load data for all sheets
  # (Defined in load_cv_sheets_helpers.R)
  # Pass down ... arguments

  # Prepare arguments explicitly
  # args_for_loader <- rlang::list2(
  #   sheet_names_to_read = load_config$sheet_names_to_read,
  #   doc_identifier = doc_identifier,
  #   ... # Capture dots with list2
  # )
  #
  # # Call the helper using do.call
  # loaded_data_list_unnamed <- do.call(.load_sheets_data, args_for_loader)

  # loaded_data_list_named <- purrr::set_names(
  #   loaded_data_list_unnamed,
  #   load_config$target_list_names
  # )

  loaded_data_list_unnamed <- .load_sheets_data(
    sheet_names_to_read = load_config$sheet_names_to_read,
    doc_identifier, #  ss_input, # Verwende das aufgelöste ss_input
    !!!list(...)
  )

  # ============================================================================
    # Phase 3: Set Names and Return
    # ============================================================================
  loaded_data_list_named <- purrr::set_names(
    loaded_data_list_unnamed,
    load_config$target_list_names
  )

  return(loaded_data_list_named)
}
