-- =============================================================================
-- 1. PERFORMANCE & CONSTANTS
-- =============================================================================

local table_insert = table.insert
local table_concat = table.concat
local string_gsub  = string.gsub
local pandoc_type  = pandoc.utils.type
local pandoc_str   = pandoc.utils.stringify
local pandoc_raw   = pandoc.RawBlock

local TYPST_META_KEY   = "definitions-01a-injected-meta-data"
local PANDOC_FMT_TYPST = "typst"

-- Single-pass substitution table for Typst string escaping
local CHAR_ESCAPE_MAP = {
  ["\\"] = "\\\\",
  ['"']  = '\\"'
}


-- =============================================================================
-- 2. CORE UTILITIES
-- =============================================================================

local function sanitize_string_for_typst(text)
  if text == nil then return '""' end
  -- Typst strings require escaping of backslashes and double quotes to prevent syntax errors.
  return '"' .. tostring(text):gsub('[\\"]', CHAR_ESCAPE_MAP) .. '"'
end

local function is_lua_table_an_array(tbl)
  -- Lua tables are hybrid. We treat empty tables as arrays to map to Typst '()'.
  if next(tbl) == nil then return true end

  local expected_index = 1
  for key, _ in pairs(tbl) do
    if key ~= expected_index then return false end
    expected_index = expected_index + 1
  end
  return true
end

local function is_typst_value_valid(typst_string)
  if not typst_string then return false end

  -- We filter out "empty" values to keep the generated Typst dictionary clean.
  -- 'none', '()', and '""' are considered noise in this context.
  if typst_string == "none" then return false end
  if typst_string == '()' then return false end
  if typst_string == '""' then return false end

  -- Filter out error comments generated by the converter
  if typst_string:match("^%(%s*%/%*") then return false end

  return true
end


-- =============================================================================
-- 3. SERIALIZATION STRATEGIES
-- =============================================================================

-- Forward declaration required for recursive calls in handlers
local convert_node_to_typst

local function serialize_as_typst_array(tbl)
  local parts = {}
  for _, item in ipairs(tbl) do
    table_insert(parts, convert_node_to_typst(item))
  end

  -- A trailing comma is required in Typst to distinguish a single-element array '(item,)'
  -- from a parenthesized expression '(item)'.
  local suffix = (#parts > 0) and "," or ""
  return '(' .. table_concat(parts, ", ") .. suffix .. ')'
end

local function serialize_as_typst_dictionary(tbl)
  local parts = {}
  for key, item in pairs(tbl) do
    -- Keys must be quoted (e.g. "my-key") to support hyphens, which are common in YAML.
    local typst_key = '"' .. tostring(key) .. '"'
    table_insert(parts, typst_key .. ": " .. convert_node_to_typst(item))
  end
  return '(' .. table_concat(parts, ", ") .. ')'
end

local function handle_generic_table(val)
  if is_lua_table_an_array(val) then
    return serialize_as_typst_array(val)
  end
  return serialize_as_typst_dictionary(val)
end

local function flatten_pandoc_content(val)
  return sanitize_string_for_typst(pandoc_str(val))
end

local function handle_primitive(val)
  return tostring(val)
end

-- Dispatch Table: Maps Pandoc/Lua types to specific handler functions.
-- This replaces complex if/else chains and ensures O(1) dispatch.
local PANDOC_TYPE_HANDLERS = {
  -- Primitives
  string   = function(val) return sanitize_string_for_typst(val) end,
  boolean  = handle_primitive,
  number   = handle_primitive,

  -- Pandoc AST Content (flattened to string for metadata usage)
  Inlines  = flatten_pandoc_content,
  Blocks   = flatten_pandoc_content,

  -- Containers (Explicit mapping for all Pandoc types)
  List     = serialize_as_typst_array,
  MetaList = serialize_as_typst_array,
  Map      = serialize_as_typst_dictionary,
  MetaMap  = serialize_as_typst_dictionary,

  -- Generic Lua Table (fallback)
  table    = handle_generic_table
}

convert_node_to_typst = function(val)
  if val == nil then return "none" end

  local meta_type = pandoc_type(val)
  local handler = PANDOC_TYPE_HANDLERS[meta_type]

  if handler then
    return handler(val)
  end

  return "(/* Unhandled Pandoc Meta type: " .. meta_type .. " */)"
end


-- =============================================================================
-- 4. MAIN PROCESSING LOGIC
-- =============================================================================

local function process_top_level_entry(key, value, target_list)
  if type(key) ~= 'string' or key == "" then return end

  local typst_value = convert_node_to_typst(value)

  if is_typst_value_valid(typst_value) then
    table_insert(target_list, '  "' .. key .. '": ' .. typst_value)
  end
end

local function construct_typst_variable(entries)
  local body = table_concat(entries, ",\n")
  return "#let meta-data = (\n" .. body .. "\n)\n"
end


-- =============================================================================
-- 5. MAIN ENTRY POINT
-- =============================================================================

function Pandoc(doc)
  local quarto_meta = doc.meta or {}
  local typst_entries = {}

  for key, value in pairs(quarto_meta) do
    process_top_level_entry(key, value, typst_entries)
  end

  local typst_code = construct_typst_variable(typst_entries)

  -- Inject as a RawBlock so Typst interprets it as code, not text content.
  doc.meta[TYPST_META_KEY] = pandoc_raw(PANDOC_FMT_TYPST, typst_code)

  return doc
end
