// typst/template.typ
// This is the main entry point for the Quarto-Typst template.
// It orchestrates the inclusion of all partials, ensuring that definitions
// are loaded before content, and that the layout structure is respected.

// ================
// 1. Definitions
// ================

// Import standard definitions generated by Quarto or the extension
$definitions.typ()$

// Load helper functions used throughout the template
$01-definitions-helper-functions.typ()$

// Load metadata injected by the Lua filter (inject_metadata.lua)
$02-definitions-metadata.typ()$

// Load visual style definitions (colors, fonts)
$03-definitions-styling.typ()$

// Load component logic (Title page, CV entries, etc.)
$04-definitions-parts-functions.typ()$

// ================
// 2. Content
// ================

// Load the main document logic (the 'resume' function)
$typst-template.typ()$

// Apply page settings
$page.typ()$

// Render any header includes defined in YAML
$for(header-includes)$
$header-includes$
$endfor$


// Apply 'show' rules to customize element rendering
$typst-show.typ()$

// Render content before the body (rarely used but good practice)
$for(include-before)$
$include-before$
$endfor$

// The main document body content
$body$

// Render notes (if applicable)
$notes.typ()$

// Render bibliography
$biblio.typ()$

// Render content after the body
$for(include-after)$
$include-after$
$endfor$
