# Filename: .github/workflows/publish.yml

name: Render, Commit MDs, and Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Set up Quarto and R (if R code is present)
      - name: Set up Quarto and R
        uses: quarto-dev/quarto-actions/setup@v2

      # 3. Render Quarto Website
      - name: Render Quarto Website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: docs

      # 4. Move MD files to offline directory
      - name: Move intermediate Markdown files
        run: |
          # 1. Handle Offline Documentation
          mkdir -p _extensions/academicCVTemplate/docs
          find docs/ -type f -name "*.md" -exec mv {} _extensions/academicCVTemplate/docs/ \;
        shell: bash

      # 5. Commit changed MD files back to 'main'
      - name: Commit offline MD docs back to main
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Docs: Update offline markdown documentation [skip ci]"
          branch: main
          file_pattern: |
            _extensions/academicCVTemplate/docs/*.md
          repository: .
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages
          force_orphan: true
